### ISSUE TITLE
IllegalArgumentException: A metric named jvm.attribute.vendor already exists

### ISSUE THREAD

**Issue by francjohny** [kenshoo/metrics-play#74]
### What happened?
Experiencing the following issue `IllegalArgumentException: A metric named jvm.attribute.vendor already exists` while running scala tests:
```
[info] Caused by: java.lang.IllegalArgumentException: A metric named jvm.attribute.vendor already exists
[info] 	at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:91)
[info] 	at com.codahale.metrics.MetricRegistry.registerAll(MetricRegistry.java:495)
[info] 	at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:85)
[info] 	at com.kenshoo.play.metrics.MetricsImpl.setupJvmMetrics(Metrics.scala:52)
[info] 	at com.kenshoo.play.metrics.MetricsImpl.onStart(Metrics.scala:72)
[info] 	at com.kenshoo.play.metrics.MetricsImpl.<init>(Metrics.scala:83)
[info] 	at com.kenshoo.play.metrics.MetricsImpl$$FastClassByGuice$$61e474d0.newInstance(<generated>)
[info] 	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
...
```
### How to reproduce?
Run the tests after injecting `met: Metrics` into your Play application
```
sbt test
```

### Similar issues:
https://github.com/addthis/metrics-reporter-config/issues/42

**Comment by tzachz** [comment]
It seems like your tests somehow leave the default `MetricRegistry` instance in the static `SharedMetricRegistries`, so two consecutive tests where each one creates an instance of `MetricsImpl` would try to re-register the same metrics, which `MetricRegistry` won't allow.

Some possible solutions / workarounds:
 - Make sure you don't have multiple tests starting the Play application running _concurrently_ on the same process - this means you can't have `fork := false` and `parallelExecution := true` both set in your SBT build, because this would mean two tests can use the same `MetricRegistry` at the same time, thus trying to register the same metrics twice
 - Make sure you properly shot down the Play application in each test that starts it - `MetricsImpl` adds a "stop hook" that removes the `MetricRegistry` from the static `SharedMetricRegistries` when the application is stopped, this exception hints that it might not be stopped between tests
 - Call `SharedMetricRegistries.clear()` after each test that uses `Metrics` (e.g. each test that actually starts the Play application or the Guice module) to "manually" force the same outcome of the stop hook
 - Disable all the "common" metrics in your test, by setting `metrics.jvm` and `metrics.logback` to `false` in your `application.conf` used in tests. This might not solve issues with similar metrics registered in your own code though, and is not recommended for production configuration because these metrics won't be reported

Hope this helps; If not - please provide more details, such as which tests cause this (you'll have to try to narrow it down) and some of the relevant build settings. Other than making sure each test starts with a "clean slate", there's not much we can do in this project to resolve this because the constraint is part of `Metrics` itself.

**Comment by francjohny** [comment]
Thanks a lot @tzachz! You were right. As a fix for now, I applied the most tempting 3rd solution as you mentioned `SharedMetricRegistries.clear() ` to all the tests and it worked.

**Comment by tzachz** [comment]
Glad to help; Closing the case, feel free to re-open if you encounter a related issue.
